package AplikasiPenjualan;

import AplikasiPenjualan.ServerAPI.ServerAPI;

public class LoginFrame extends javax.swing.JFrame {

    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginPage = new javax.swing.JPanel();
        pageTitle = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        labelInputNama = new javax.swing.JLabel();
        LabelInputPassword = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        errorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penjualan");
        setLocation(new java.awt.Point(150, 50));

        loginPage.setPreferredSize(new java.awt.Dimension(1000, 800));

        pageTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        pageTitle.setText("LOGIN");

        inputNama.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inputNama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        inputNama.setMinimumSize(new java.awt.Dimension(700, 50));
        inputNama.setPreferredSize(new java.awt.Dimension(700, 50));

        labelInputNama.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelInputNama.setText("Nama        :");

        LabelInputPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelInputPassword.setText("Password :");

        inputPassword.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        inputPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        inputPassword.setMinimumSize(new java.awt.Dimension(16, 24));
        inputPassword.setPreferredSize(new java.awt.Dimension(16, 24));

        submitButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        errorMessage.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        errorMessage.setText("Nama atau Password yang anda masukan salah");

        javax.swing.GroupLayout loginPageLayout = new javax.swing.GroupLayout(loginPage);
        loginPage.setLayout(loginPageLayout);
        loginPageLayout.setHorizontalGroup(
            loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(446, 446, 446))
            .addGroup(loginPageLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPageLayout.createSequentialGroup()
                        .addComponent(LabelInputPassword)
                        .addGap(61, 61, 61)
                        .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPageLayout.createSequentialGroup()
                        .addComponent(labelInputNama)
                        .addGap(58, 58, 58)
                        .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorMessage)
                            .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginPageLayout.createSequentialGroup()
                    .addGap(458, 458, 458)
                    .addComponent(pageTitle)
                    .addContainerGap(458, Short.MAX_VALUE)))
        );
        loginPageLayout.setVerticalGroup(
            loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPageLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInputNama))
                .addGap(18, 18, 18)
                .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelInputPassword))
                .addGap(24, 24, 24)
                .addComponent(submitButton)
                .addContainerGap(462, Short.MAX_VALUE))
            .addGroup(loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginPageLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(pageTitle)
                    .addContainerGap(721, Short.MAX_VALUE)))
        );

        errorMessage.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //authenticate user
        String nama = inputNama.getText();
        String pswd = String.copyValueOf(inputPassword.getPassword());
        if(ServerAPI.login_authentication(nama, pswd)){
            //navigate to mainPage
            System.out.println("\nNavigate to mainPage");
            int idUser = ServerAPI.getIdUser(nama, pswd);
            new MainFrame(idUser).setVisible(true);
            this.dispose();
        }else{
            errorMessage.setVisible(true);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelInputPassword;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JTextField inputNama;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInputNama;
    private javax.swing.JPanel loginPage;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables

    //my own declaration
}
