/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AplikasiPenjualan;

import AplikasiPenjualan.ServerAPI.ServerAPI;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Lenovo
 */
public class LogPage extends javax.swing.JPanel {

    /**
     * Creates new form LogPage
     */
    public LogPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pageTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1200, 800));

        pageTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pageTitle.setText("Log Penjualan");

        dataTable.getTableHeader().setFont(new java.awt.Font("Arial", 0, 16));
        dataTable.getTableHeader().setBackground(Color.BLACK);
        dataTable.getTableHeader().setForeground(Color.WHITE);
        dataTable.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Tanggal", "Total", "Detail Barang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) dataTable.getModel();
        ArrayList<ArrayList<String>> data = ServerAPI.get_data_laporan();
        for(ArrayList<String> d : data){
            tableModel.addRow(d.toArray());
        }
        jScrollPane1.setViewportView(dataTable);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(0).setMinWidth(200);
            dataTable.getColumnModel().getColumn(0).setPreferredWidth(200);
            dataTable.getColumnModel().getColumn(0).setMaxWidth(200);
            dataTable.getColumnModel().getColumn(1).setMinWidth(200);
            dataTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            dataTable.getColumnModel().getColumn(1).setMaxWidth(200);
            dataTable.getColumnModel().getColumn(2).setMinWidth(200);
            dataTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            dataTable.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(546, Short.MAX_VALUE)
                .addComponent(pageTitle)
                .addGap(498, 498, 498))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pageTitle)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pageTitle;
    // End of variables declaration//GEN-END:variables

    //my own declaration
    public void refresh(){
        System.out.print("\nRefreshing log page...");
        javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) dataTable.getModel();
        int rowCount = dataTable.getRowCount();
        for(int i=0; i<rowCount; ++i){
            tableModel.removeRow(0);
        }
        
        ArrayList<ArrayList<String>> data = ServerAPI.get_data_laporan();
        for(ArrayList<String> d : data){
            tableModel.addRow(d.toArray());
        }
    }
}
