/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package AplikasiPenjualan;

import AplikasiPenjualan.ServerAPI.ServerAPI;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.SwingUtilities;

/**
 *
 * @author Lenovo
 */
public class SelectBarangDialog extends javax.swing.JDialog {

    /**
     * Creates new form SelectBarangDialog
     */
    public SelectBarangDialog(TransaksiPage parentPage, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parentPage;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        pageTitle = new javax.swing.JLabel();
        pilihBarangButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dataTable.getTableHeader().setFont(new java.awt.Font("Arial", 0, 16));
        dataTable.getTableHeader().setBackground(Color.BLACK);
        dataTable.getTableHeader().setForeground(Color.WHITE);
        dataTable.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Barang", "Harga", "Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable.setPreferredSize(new java.awt.Dimension(1200, 800));
        dataTable.setRowHeight(20);
        dataTable.getTableHeader().setReorderingAllowed(false);

        //get data barang from DB and addding it to table
        javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) dataTable.getModel();
        ArrayList<String[]> dataBarang = ServerAPI.get_data_barang();
        for(String[] row : dataBarang){
            tableModel.addRow(row);
        }

        jScrollPane1.setViewportView(dataTable);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(0).setMinWidth(70);
            dataTable.getColumnModel().getColumn(0).setPreferredWidth(70);
            dataTable.getColumnModel().getColumn(0).setMaxWidth(70);
            dataTable.getColumnModel().getColumn(3).setMinWidth(70);
            dataTable.getColumnModel().getColumn(3).setPreferredWidth(70);
            dataTable.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        pageTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pageTitle.setText("Pilih Barang");

        pilihBarangButton.setText("Pilih");
        pilihBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihBarangButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pageTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pilihBarangButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pilihBarangButton)
                    .addComponent(pageTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihBarangButtonActionPerformed
        int[] selected = dataTable.getSelectedRows();
        ArrayList<String> selectedID = new ArrayList<String>();
        
        for(int d : selected){
            selectedID.add((String) dataTable.getValueAt(d, 0));
            System.out.print("selected : "+d);
        }
        this.dispose();
        parent.addSelectedBarang(selectedID);
        System.out.print("\nPilih Barang butto had pressed");
    }//GEN-LAST:event_pilihBarangButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JButton pilihBarangButton;
    // End of variables declaration//GEN-END:variables

    //my own declaration
    private TransaksiPage parent;
}
